import type { CSSProperties } from "react";

/**
 * Prism theme tuned to Codex-style previews: warm keywords, soft green
 * strings, bright default text on a transparent card body.
 */
export const codexPrismStyle: { [key: string]: CSSProperties } = {
  'code[class*="language-"]': {
    color: "#e8e8e8",
    background: "transparent",
    textShadow: "none",
    fontFamily:
      'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
    fontSize: "13px",
    lineHeight: "1.55",
    direction: "ltr",
    textAlign: "left",
    whiteSpace: "pre",
    wordSpacing: "normal",
    wordBreak: "normal",
    MozTabSize: "2",
    OTabSize: "2",
    tabSize: "2",
    WebkitHyphens: "none",
    MozHyphens: "none",
    msHyphens: "none",
    hyphens: "none",
  },
  'pre[class*="language-"]': {
    color: "#e8e8e8",
    background: "transparent",
    textShadow: "none",
    fontFamily:
      'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
    fontSize: "13px",
    lineHeight: "1.55",
    direction: "ltr",
    textAlign: "left",
    whiteSpace: "pre",
    wordSpacing: "normal",
    wordBreak: "normal",
    MozTabSize: "2",
    OTabSize: "2",
    tabSize: "2",
    WebkitHyphens: "none",
    MozHyphens: "none",
    msHyphens: "none",
    hyphens: "none",
    padding: "0",
    margin: "0",
    overflow: "auto",
  },
  ':not(pre) > code[class*="language-"]': {
    background: "transparent",
    padding: "0",
  },
  comment: { color: "#6b737c" },
  prolog: { color: "#6b737c" },
  doctype: { color: "#6b737c" },
  cdata: { color: "#6b737c" },
  punctuation: { color: "#c8c8c8" },
  property: { color: "#e8e8e8" },
  tag: { color: "#e5a46c" },
  boolean: { color: "#e5a46c" },
  number: { color: "#e5a46c" },
  constant: { color: "#e5a46c" },
  symbol: { color: "#e5a46c" },
  deleted: { color: "#e5a46c" },
  selector: { color: "#a8d08d" },
  "attr-name": { color: "#e8e8e8" },
  string: { color: "#a8d08d" },
  char: { color: "#a8d08d" },
  builtin: { color: "#a8d08d" },
  inserted: { color: "#a8d08d" },
  operator: { color: "#e8e8e8" },
  entity: { color: "#e8e8e8", cursor: "help" },
  url: { color: "#a8d08d" },
  ".language-css .token.string": { color: "#a8d08d" },
  ".style .token.string": { color: "#a8d08d" },
  atrule: { color: "#e5a46c" },
  "attr-value": { color: "#a8d08d" },
  keyword: { color: "#e5a46c" },
  function: { color: "#e8e8e8" },
  "class-name": { color: "#e8e8e8" },
  regex: { color: "#a8d08d" },
  important: { color: "#e5a46c", fontWeight: "bold" },
  variable: { color: "#e8e8e8" },
  bold: { fontWeight: "bold" },
  italic: { fontStyle: "italic" },
  namespace: { color: "#e8e8e8" },
  parameter: { color: "#e8e8e8" },
};
